services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: bookdatabase
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql
      - ./bookdatabase.sql:/docker-entrypoint-initdb.d/bookdatabase.sql
    networks:
      - booktrack_network

  backend:
    build: ./backend
    container_name: booktrack_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/bookdatabase
    volumes:
      - ./backend:/app        # ← hot reload : tes modifications s'appliquent direct
    depends_on:
      - postgres
    networks:
      - booktrack_network

  frontend:
    build: ./frontend
    container_name: booktrack_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000      # ← navigateur
      API_URL: http://backend:8000                    # ← serveur Docker
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - booktrack_network

volumes:
  pg_data:

networks:
  booktrack_network:
    driver: bridge