services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: bookdatabase
    ports:
      - "5431:5432"
    volumes:
      - ./bookdatabase.sql:/docker-entrypoint-initdb.d/bookdatabase.sql